#cloud-config
package_update: true
package_upgrade: true
packages:
- jq
- ldap-utils
- neovim
- netcat-openbsd
- nmap
- openvpn
- podman
- smbclient
- socat
users:
- name: sliver
  primary_group: users
  lock_passwd: true
  shell: /bin/bash
  sudo: ALL=(ALL) NOPASSWD:ALL
mounts:
- [ /dev/disk/by-id/scsi-0HC_Volume_${volume_id}, /home/sliver, ext4, 'defaults,nofail,discard', '0', '0' ]
write_files:
- path: /etc/ssh/sshd_config.d/hardening.conf
  content: |
    PubkeyAuthentication yes
    PasswordAuthentication no
- path: /etc/nftables.conf
  content: |
    #!/usr/sbin/nft -f

    flush ruleset

    table inet filter {
      chain input {
        type filter hook input priority 0
        policy accept
        ct state { established, related } accept
        ct state invalid drop
        iifname "eth0" tcp dport != { 22, 31337 } drop
      }

      chain forward {
        type filter hook forward priority 0
        policy accept
        ct state { established, related } accept
        ct state invalid drop
        iifname "eth0" drop
      }

      chain output {
        type filter hook output priority 0
        policy accept
      }
    }
- path: /etc/systemd/system/sliver.service
  content: |
    [Unit]
    Description=Sliver Server
    Wants=network.target
    After=network.target

    [Service]
    Type=simple
    ExecStartPre=bash -c 'until mountpoint -q /home/sliver; do sleep 10; done'
    ExecStart=sliver-server daemon
    User=sliver
    WorkingDirectory=/home/sliver
    CapabilityBoundingSet=cap_net_bind_service
    AmbientCapabilities=cap_net_bind_service

    [Install]
    WantedBy=multi-user.target
runcmd:
- curl -sSf -o /tmp/releases.json https://api.github.com/repos/bishopfox/sliver/releases/latest
- jq -r '.assets[]|select(.name=="sliver-server_linux")|.browser_download_url' /tmp/releases.json | wget -i - -O /usr/local/bin/sliver-server
- jq -r '.assets[]|select(.name=="sliver-client_linux")|.browser_download_url' /tmp/releases.json | wget -i - -O /usr/local/bin/sliver-client
- chmod +x /usr/local/bin/sliver-server /usr/local/bin/sliver-client
- setcap CAP_NET_BIND_SERVICE+ep /usr/local/bin/sliver-server
- systemctl enable nftables.service sliver.service
- reboot
